"""Per-game fantasy point production for every TI2026 player.

Fantasy pairs players by role -- core is a team's safelane+offlane, support is
its two supports, mid is one player -- so the first job is working out who
plays what. That is inferred from the games themselves (farm share, ward
placement, stacking) rather than assumed.

Then every game is converted into the 18 fantasy stat lines, so we can ask
"what is this stat worth for this player" instead of guessing from reputation.

Two of the 18 (Watchers Taken, Lotuses Grabbed) are not exposed by OpenDota and
come out as NaN; they are flagged rather than silently zeroed.
"""

import collections
import datetime as dt
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# base points, from the client's Fantasy help screen
BASE = {
    "kills": 107.0,
    "deaths": -195.0,          # applied to death count; 1950 starting points
    "cs": 3.0,                 # last hits + denies
    "gpm": 2.0,                # multiplied by GPM
    "madstone": 13.0,
    "towers": 352.0,
    "wards": 117.0,
    "stacks": 234.0,
    "runes": 141.0,
    "watchers": 147.0,         # not available from OpenDota
    "lotus": 176.0,            # not available from OpenDota
    "roshan": 1172.0,
    "teamfight": 2124.0,       # max, scaled by participation fraction
    "stuns": 10.0,             # per second
    "tormentor": 879.0,
    "courier": 703.0,
    "firstblood": 1934.0,
    "smokes": 293.0,
}
DEATH_BASE = 1950.0
UNAVAILABLE = {"watchers", "lotus"}

COLOR = {
    "red": ["kills", "deaths", "cs", "gpm", "madstone", "towers"],
    "blue": ["wards", "stacks", "runes", "watchers", "smokes", "lotus"],
    "green": ["roshan", "teamfight", "stuns", "tormentor", "firstblood", "courier"],
}


def game_stats(r):
    """One player-game -> raw fantasy quantities (not yet points)."""
    killed = r.get("killed") or {}
    uses = r.get("item_uses") or {}
    return {
        "kills": r.get("kills") or 0,
        "deaths": r.get("deaths") or 0,
        "cs": (r.get("last_hits") or 0) + (r.get("denies") or 0),
        "gpm": r.get("gold_per_min") or 0,
        # Valve calls this stat NeutralTokensFound. OpenDota's matching field,
        # neutral_tokens_log, is empty on every current-patch parse, but each
        # madstone pickup fires an item-use event on the bundle, so the use
        # count stands in for the pickup count.
        "madstone": uses.get("madstone_bundle", 0),
        "towers": r.get("towers_killed") or 0,
        "wards": r.get("obs_placed") or 0,
        "stacks": r.get("camps_stacked") or 0,
        "runes": r.get("rune_pickups") or 0,
        "watchers": np.nan,
        "lotus": np.nan,
        "roshan": r.get("roshans_killed") or 0,
        "teamfight": r.get("teamfight_participation") or 0.0,
        "stuns": r.get("stuns") or 0.0,
        "tormentor": killed.get("npc_dota_miniboss", 0),
        "courier": killed.get("npc_dota_courier", 0),
        "firstblood": r.get("firstblood_claimed") or 0,
        "smokes": uses.get("smoke_of_deceit", 0),
    }


def to_points(q):
    """Raw quantities -> fantasy points, per stat, as they'd score alone."""
    p = {}
    for k, v in q.items():
        if k == "deaths":
            p[k] = DEATH_BASE + BASE["deaths"] * v
        elif k == "teamfight":
            p[k] = BASE["teamfight"] * v
        else:
            p[k] = BASE[k] * v
    return p


def apply_roster_overrides(teams):
    """Apply data/roster_overrides.json on top of the fetched rosters.

    teams.json is regenerated by fetch_teams.py from OpenDota, which lags roster
    moves that happen after the client's official list was published (LGD's mid
    was ruled out of TI2026 over a competitive-integrity decision in 2026-08 and
    replaced by Topson -- see docs/08-roster.md 5). Overrides
    live in their own file so a refetch cannot silently drop them.
    """
    path = os.path.join(ROOT, "data", "roster_overrides.json")
    if not os.path.exists(path):
        return teams
    ov = json.load(open(path))
    out = dict(teams)
    for name, spec in ov.items():
        if name not in out:
            continue
        gone = {d["account_id"] for d in spec.get("drop", [])}
        players = [p for p in out[name]["players"] if p["account_id"] not in gone]
        have = {p["account_id"] for p in players}
        for a in spec.get("add", []):
            if a["account_id"] not in have:
                # games_played only orders the roster; the real count comes from
                # the match sample, so a placeholder is enough to keep the five.
                players.append({"account_id": a["account_id"], "name": a["name"],
                                "games_played": 0, "wins": 0})
        out[name] = dict(out[name], players=players)
    return out


def assign_roles(rows_by_player, teams):
    """Infer position from play patterns, then map onto fantasy's three slots.

    Cores farm (high last hits, few wards); supports ward and stack. Which of
    the three cores plays mid comes from OpenDota's parsed `lane_role`
    (1 safe / 2 mid / 3 off), not from XPM -- in the current meta the carry
    usually out-XPMs the midlaner, so an XPM heuristic picks the wrong player
    on most teams.
    """
    out = {}
    for name, info in apply_roster_overrides(teams).items():
        # teams.json lists players by lifetime games, which picks up veterans
        # who have since left the active roster (OG's Ceb: 931 career games,
        # 10 in the sample window). Take the five who actually play now.
        accs = sorted((p["account_id"] for p in info["players"]),
                      key=lambda a: -len(rows_by_player.get(a, [])))[:5]
        prof = {}
        for a in accs:
            g = rows_by_player.get(a, [])
            if not g:
                continue
            lanes = collections.Counter(x.get("lane_role") for x in g
                                        if x.get("lane_role"))
            prof[a] = {
                "gpm": np.mean([x.get("gold_per_min") or 0 for x in g]),
                "lh": np.mean([x.get("last_hits") or 0 for x in g]),
                "xpm": np.mean([x.get("xp_per_min") or 0 for x in g]),
                "wards": np.mean([x.get("obs_placed") or 0 for x in g]),
                "stacks": np.mean([x.get("camps_stacked") or 0 for x in g]),
                "mid_share": lanes.get(2, 0) / max(sum(lanes.values()), 1),
                "safe_share": lanes.get(1, 0) / max(sum(lanes.values()), 1),
                "n": len(g),
            }
        if len(prof) < 5:
            out[name] = None
            continue
        farm = {a: prof[a]["lh"] + prof[a]["gpm"] * 0.5 - prof[a]["wards"] * 40 for a in prof}
        ordered = sorted(prof, key=lambda a: -farm[a])
        cores3, sups2 = ordered[:3], ordered[3:]
        mid = max(cores3, key=lambda a: prof[a]["mid_share"])
        core_pair = [a for a in cores3 if a != mid]
        out[name] = {"core": core_pair, "mid": [mid], "support": sups2, "profile": prof}
    return out


def load(min_date="2025-10-01", tiers=("premium", "professional")):
    with open(os.path.join(ROOT, "data", "raw", "player_matches.json")) as f:
        pm = json.load(f)
    cut = int(dt.datetime.fromisoformat(min_date).replace(
        tzinfo=dt.timezone.utc).timestamp())
    keep = [r for r in pm if r["start_time"] >= cut and r.get("tier") in tiers]
    by_player = collections.defaultdict(list)
    for r in keep:
        by_player[r["account_id"]].append(r)
    return keep, by_player


def main():
    teams = json.load(open(os.path.join(ROOT, "data", "teams.json")))
    rows, by_player = load()
    print(f"{len(rows)} player-games since 2025-10 in top-tier events\n")

    roles = assign_roles(by_player, teams)
    names = {p["account_id"]: p["name"]
             for t in teams.values() for p in t["players"]}

    print(f"{'team':<18}{'core (1+3)':<28}{'mid':<14}{'support (4+5)':<26}")
    for t, r in roles.items():
        if not r:
            print(f"{t:<18}  -- insufficient data --")
            continue
        c = "+".join(names.get(a, str(a)) for a in r["core"])
        m = names.get(r["mid"][0], "?")
        s = "+".join(names.get(a, str(a)) for a in r["support"])
        print(f"{t:<18}{c:<28}{m:<14}{s:<26}")

    # per-player mean fantasy points by stat
    print(f"\nmean fantasy points per game, by stat "
          f"(NaN = OpenDota does not expose it)")
    stat_order = COLOR["red"] + COLOR["blue"] + COLOR["green"]
    hdr = "".join(f"{s[:7]:>8}" for s in stat_order)
    print(f"{'player':<14}{'role':<8}{hdr}")
    table = {}
    for t, r in roles.items():
        if not r:
            continue
        for role in ("core", "mid", "support"):
            for a in r[role]:
                g = by_player.get(a, [])
                if len(g) < 15:
                    continue
                pts = [to_points(game_stats(x)) for x in g]
                mean = {s: float(np.nanmean([p[s] for p in pts])) for s in stat_order}
                table[a] = {"team": t, "role": role, "n": len(g), "mean": mean}
    for a, v in sorted(table.items(), key=lambda kv: (kv[1]["team"], kv[1]["role"])):
        cells = "".join(f"{v['mean'][s]:>8.0f}" if np.isfinite(v["mean"][s])
                        else f"{'--':>8}" for s in stat_order)
        print(f"{names.get(a, str(a))[:13]:<14}{v['role']:<8}{cells}")

    json.dump({str(k): v for k, v in table.items()},
              open(os.path.join(ROOT, "data", "fantasy_player_stats.json"), "w"),
              indent=1)
    json.dump({t: (None if not r else
                   {k: r[k] for k in ("core", "mid", "support")})
               for t, r in roles.items()},
              open(os.path.join(ROOT, "data", "roles.json"), "w"), indent=1)


if __name__ == "__main__":
    main()
